### ISSUE TITLE
Can this handle non-python packages?

### ISSUE THREAD

**Issue by costrouc** [t184256/nixpkgs-python-importer#8]
First off this tool is amazing! Thank you an I would like to help since this is such a neat project.

Lets say that I want to install the `tree` utility with `from nixpkgs....` would this be possible. I imaging all the would have to be overwritten is the `PATH`?

**Comment by t184256** [comment]
I'm afraid I don't really understand what you're going after.

Are you trying to run `tree` from your shell? That's basically `nix run nixpkgs.tree -c tree`.

Are you trying to run `tree` from your shell without a subshell?

Do you want to be able to do something in Python to be able to launch `tree` using `subprocess`?

**Comment by costrouc** [comment]
> Do you want to be able to do something in Python to be able to launch tree using subprocess?

Yes. `tree` would not tnecissarily be the command I would want. Basically the ability to add executables to the path dynamically in python.

I really want to use this with https://github.com/costrouc/nix-binder-example that I developed. It would allow on the fly package imports in jupyter notebooks. I can envision at times that other packages would be needed such as `nodejs`, and who knows what.

**Comment by t184256** [comment]
> Basically the ability to add executables to the path dynamically in python.

OK, how it should be different from / better than running `nix run nixpkgs.tree -c tree` from within python using `subprocess`?

**Comment by costrouc** [comment]
Because I am looking for a solution where the user does not need to know that they are even using nix. The nixpkgs python naming is somewhat consistent with pypi thus users can reasonably expect `from nixpkgs.<package> import <package>` will work for packages

**Comment by t184256** [comment]
(Sorry that this is getting somewhat inquisitive.)

OK, so you want to instantiate a package, add its `/bin` into `$PATH` and, as a result, allow your child processes to run its binaries.

This seems like quite a separate goal that is not really related to Python import machinery. In fact, I don't even think that the import syntax is a good fit here. It is designed for importing Python modules, and `from nixpkgs.pbr import pbr` leaves me with the `pbr' module accessible as `pbr`, but what should `tree` be after `from nixpkgs.tree import tree`?

Looks like you have a slightly related goal and a solid plan, but, at the same time, these call for quite different syntax and implementation.

**Comment by adisbladis** [comment]
I like the spirit of the idea but I don't think that feature belongs in this module.
The functionality you want could be implemented in a much smaller module without abusing the python `import` statement.

It's also worth noting that `from nixpkgs.<attr>` accesses attr from `python3Packages` and _not_ from the nixpkgs root.
This is a behaviour I wouldn't want to change.

**Comment by costrouc** [comment]
Okay good to know. Yes you are right that not using the import statement would be a better approach. But my point is that many python packages **depend** on executables which are not included in the derivations and it would be nice to have a way to add them with this package. Take for example `graphviz` https://pypi.org/project/graphviz/. 

```
>>> from nixpkgs.graphviz import graphviz
>>> dot = graphviz.Digraph(comment='The Round Table')
>>> dot.node('A', 'King Arthur')
>>> dot.render('test-output/round-table.gv', view=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/ci0vq8q4vacgy900si8zxnjkkhpix37z-python3.7-graphviz-0.10.1/lib/python3.7/site-packages/graphviz/files.py", line 194, in render
    self._view(rendered, self._format)
  File "/nix/store/ci0vq8q4vacgy900si8zxnjkkhpix37z-python3.7-graphviz-0.10.1/lib/python3.7/site-packages/graphviz/files.py", line 230, in _view
    view_method(filepath)
  File "/nix/store/ci0vq8q4vacgy900si8zxnjkkhpix37z-python3.7-graphviz-0.10.1/lib/python3.7/site-packages/graphviz/backend.py", line 255, in view_unixoid
    subprocess.Popen(['xdg-open', filepath])
  File "/nix/store/4ag8gng51y7yw6nr3imwyppqfci3j643-python3-3.7.2/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/nix/store/4ag8gng51y7yw6nr3imwyppqfci3j643-python3-3.7.2/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open': 'xdg-open'
```

So even if this import will get graphviz it will not be able to add `xdg-open` to the path to view.

I see the potential for this to be the ultimate sandbox and being able to adhoc build nix derivations  enables this.

**Comment by adisbladis** [comment]
@costrouc I hacked together a gist doing what you want: https://gist.github.com/adisbladis/6a152e6108f57a5071a441fcecb00395.

**Comment by costrouc** [comment]
I will close this issue and instead persue a fork to experiment with what this looks like. Thanks @adisbladis and thank you for bringing this awesome project to my attention.
